config/routes.rb
Spellchecker::Application.routes.draw do
  get "documentation/install"
  get "documentation/languages"
  get "documentation/api"
  resources :domains

	root 'main#index'
	
	post "api/check" => "spellcheck#check"
	get "api/check" => "spellcheck#check"
  
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
		get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
		get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
	end
	get "locale", to: "application#set_locale"
end

app/models/domain.rb
class Domain < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :omniauthable
	
	has_many :domains
	
	def self.find_or_create_for_doorkeeper_oauth(oauth_data)
		User.find_or_initialize_by_doorkeeper_uid(oauth_data.uid).tap do |user|
			user.email = oauth_data.info.email
		end
	end

	def update_doorkeeper_credentials(oauth_data)
		self.doorkeeper_access_token = oauth_data.credentials.token
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	
	before_action :set_locale
  
	def doorkeeper_oauth_client
		@client ||= OAuth2::Client.new(ENV["APP_ID"], ENV["APP_SECRET"], :site => ENV["APP_URL"])
	end

	def doorkeeper_access_token
		@token ||= OAuth2::AccessToken.new(doorkeeper_oauth_client, current_user.doorkeeper_access_token) if current_user
	end

	def auth_user
		redirect_to user_omniauth_authorize_url(:doorkeeper) unless user_signed_in?
	end
	
	def set_locale
		I18n.locale=cookies[:locale] if !cookies[:locale].nil?
		if !current_user.nil?
			I18n.locale=current_user.locale
			if !params[:locale].nil?
				current_user.locale=params[:locale]
				current_user.save
				redirect_to :back
			end
		else
			if !params[:locale].nil?
				cookies[:locale]=params[:locale]
				redirect_to :back
			end
		end
	end
	
	def new_session_path(scope)
		new_user_session_path
	end
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
  def install
  end

  def languages
  end

  def api
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
	before_action :auth_user
	before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  def index
    @domains = current_user.domains
  end

  # GET /domains/1
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  def create
    @domain = Domain.new(domain_params.merge(user: current_user))

    if @domain.save
      redirect_to domains_url, notice: t('domains.created')
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /domains/1
  def update
    if @domain.update(domain_params)
      redirect_to domains_url, notice: t('domains.updated')
    else
      render action: 'edit'
    end
  end

  # DELETE /domains/1
  def destroy
    @domain.destroy
    redirect_to domains_url, notice: t('domains.destroyed')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = current_user.domains.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def domain_params
      params.require(:domain).permit(:user_id, :name, :words, :requests)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_action :auth_user, except: [ :index ]
	def index
	end
end

app/controllers/spellcheck_controller.rb
class SpellcheckController < ApplicationController
	skip_before_filter :verify_authenticity_token
	
	LANGUAGE_BINDINGS={
		'ar'=>'ar',
		'az'	=>'az',
		'be'	=>'be_BY',
		'bg'	=>'bg_BG',
		'ca'	=>'ca',
		'cs'	=>'cs_CZ',
		'da'	=>'da_DK',
		'de'	=>'de_DE_frami',
		'el'	=>'el_GR',
		'en'	=>'en_US_large',
		'es'	=>'es_ES',
		'et'	=>'et_EE',
		'fr'	=>'fr',
		'gl'	=>'gl_ES',
		'he'	=>'he_IL',
		'hr'	=>'hr_HR',
		'hy'	=>'hy_AM',
		'it'	=>'it_IT',
		'lt'	=>'lt_LT',
		'nl'	=>'nl_NL',
		'pl'	=>'pl_PL',
		'pt'	=>'pt_BR',
		'ro'	=>'ro_RO',
		'ru'	=>'ru_RU',
		'sl'	=>'si_SI',
		'sk'	=>'sk_SK',
		'sr'	=>'sr',
		'sv'	=>'sv_SE',
		'uk'	=>'uk_UA',
		'vi'	=>'vi_VN'
	}
	
	WORDS_LIMIT=5000
	
	def check
		host=request.headers['origin'] || request.headers['referer'][/[^\/]*\:\/\/[^\/]*/]
		domain=Domain.where(name: host).first#use host for statistics and users
		if (LANGUAGE_BINDINGS[params["lang"]] && domain && domain.words<WORDS_LIMIT) then
			domain.requests+=1
			if (params['text']) then
				obj={outcome: "success"}
				data=[]
				FFI::Hunspell.dict(LANGUAGE_BINDINGS[params["lang"]]) do |dict|
					params['text'].each do |a|
						words=[]
						a.split.each do |word|
							domain.words+=1
							if (domain.words<WORDS_LIMIT)
								words<< word if (!dict.check?(word))
							end
						end
						data<<words
					end
				end
				obj[:data]=data
			elsif (params['word']) then
				FFI::Hunspell.dict(LANGUAGE_BINDINGS[params["lang"]]) do |dict|
					domain.words+=1
					obj=dict.suggest(params['word'])
				end
			end
			domain.save
		else
			obj={outcome: "failure"}
			obj[:error]="can't found #{host}" if (!domain)
			obj[:error]="limit for #{host} reached" if (domain && domain.words>WORDS_LIMIT)
		end
#		headers['Access-Control-Allow-Origin'] = '*'
#		headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
#		headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
#		headers['Access-Control-Max-Age'] = "1728000"
		render json: obj
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
	def doorkeeper
		p params
		oauth_data = request.env["omniauth.auth"]
		@user = User.find_or_create_for_doorkeeper_oauth(oauth_data)
		@user.locale=oauth_data[:info][:locale]
		@user.admin=oauth_data[:info][:admin]
		@user.time_zone=oauth_data[:info][:time_zone]
		@user.save
		cookies[:locale]=@user.locale
		
		sign_in_and_redirect @user
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def available_languages
		SpellcheckController::LANGUAGE_BINDINGS.keys
	end
end

app/helpers/documentation_helper.rb
module DocumentationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/documentation/api.html.erb
<h1><%= t("documentation.api.menu") %></h1>
<p>
	<%= t("documentation.api.translate_text_request") %>
</p>
POST/GET:
<pre style="width:200px;"><code class="language-javascript">{
	lang: "en"
	text[]: "some+word"
	text[]: "with+mistake"
}
</code></pre>
<p>
	<%= t("documentation.api.translate_text_response") %>
</p>
JSON:
<pre style="width:330px;"><code class="language-javascript">{
	"outcome": "success",
	data: [["some","word"],["with","mistake"]]
}
</code></pre>

<p>
	<%= t("documentation.api.translate_word_request") %>
</p>
POST/GET:
<pre style="width:120px;"><code class="language-javascript">{
	lang: "en"
	word: "some"
}
</code></pre>
<p>
	<%= t("documentation.api.translate_word_response") %>
</p>
JSON:
<pre style="width:120px;"><code class="language-javascript">["1","2","3","4"]
</code></pre>

app/views/documentation/config.html.erb
<h1>Documentation#install</h1>
<p>Find me in app/views/documentation/install.html.erb</p>
Full configuration

<pre><code class="javascript">{
    lang: "<%= t("documentation.config.language") %>",
    webservice: {
      path: 'http://spellchecker.wsstudio.tk/api/check'
    },
    local: {
      requestError: "<%= t("documentation.config.request_error") %>",
      ignoreWord: "<%= t("documentation.config.ignore_word") %>",
      ignoreAll: "<%= t("documentation.config.ignore_all") %>",
      ignoreForever: "<%= t("documentation.config.ignore_forever") %>",
      loading: "<%= t("documentation.config.loading") %>",
      noSuggestions: "<%= t("documentation.config.no_suggestions") %>"
    },
    suggestBox: {
      numWords: 5, //<%= t("documentation.config.num_words") %>
      position: 'above',
      offset: 2,
      appendTo: null
    }
};</code></pre>

app/views/documentation/install.html.erb
<h1>Documentation#install</h1>
<p>Find me in app/views/documentation/install.html.erb</p>

app/views/documentation/languages.html.erb
<script type="text/javascript" src="/jquery.spellchecker.js"></script>
<link rel="stylesheet" type="text/css" media="screen" href="/jquery.spellchecker.min.css" />
<style type="text/css">
  #text-content {width:400px;border:1px solid #888;padding:1em;margin:0 0 1em 0;}
</style>


<h1><%= t("documentation.languages.menu") %></h1>

<table width="100%"><tr>
	<td>
		<%= t("documentation.languages.available") %>
		<table>
			<tr><td>
				<table class="table table-bordered table-striped">
					<tr>
						<th><%= t("documentation.languages.code") %></th>
						<th><%= t("documentation.languages.name") %></th>
					</tr>
						<% available_languages.each do |l| %>
					<tr>
							<td><%= t("langs.#{l}") %></td>
							<td><%= l %></td>
					</tr>
						<% end %>
				</table>
			</td></tr>
		</table>
	</td>
	<td align=center width="35%">
		<div contenteditable=true id="text-content">
		<%= t("documentation.languages.check_text").html_safe %>
		</div>
		<select id="language">
			<% available_languages.each do |l| %>
				<option value="<%= l %>" <%= "selected" if (l==I18n.locale.to_s) %>><%= t("langs.#{l}") %></option>
			<% end %>
		</select>
		<button id="check-textarea">
		  Check Spelling
		</button>&nbsp;<br />
		<%= t("documentation.languages.usage", set_lang: "spellchecker.setLang(lang)").html_safe %>
		</div>
	</td>
	<td align=center width="35%">
		<pre ><code class="language-javascript">(function() {
  // Init the html spellchecker
  var spellchecker = new $.SpellChecker('#text-content', {
	lang: "en",
	parser: 'html',
	webservice: {
	  path: '/api/check',
	  driver: 'PSpell'
	},
	suggestBox: {
	  position: 'below'
	}
  });

  // Bind spellchecker handler functions
  spellchecker.on('check.success', function() {
	alert('There are no incorrectly spelt words!');
  });
  
  // Check the spelling
  $("#check-textarea").click(function(e){
	spellchecker.check();
  });
  
  // Change the language
  $('#language').change(function() {
	spellchecker.setLang(this.value);
  }).trigger('change');

})();</code></pre>  
	</td>
</tr></table>


<script type="text/javascript">
	(function() {
		  // Init the html spellchecker
		  var spellchecker = new $.SpellChecker('#text-content', {
			lang: "en",
			parser: 'html',
			webservice: {
			  path: '/api/check',
			  driver: 'PSpell'
			},
			suggestBox: {
			  position: 'below'
			}
		  });

		  // Bind spellchecker handler functions
		  spellchecker.on('check.success', function() {
			alert('There are no incorrectly spelt words!');
		  });
		  
		  // Check the spelling
		  $("#check-textarea").click(function(e){
			spellchecker.check();
		  });
		  
		  // Change the language
		  $('#language').change(function() {
			spellchecker.setLang(this.value);
		  }).trigger('change');
		
	})();
</script>

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<h1>Listing domains</h1>

<table>
  <thead>
    <tr>
      <th><%= t("domains.name") %></th>
      <th><%= t("domains.words") %></th>
      <th><%= t("domains.requests") %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.name %></td>
        <td><%= domain.words %></td>
        <td><%= domain.requests %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>New domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @domain.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @domain.name %>
</p>

<p>
  <strong>Words:</strong>
  <%= @domain.words %>
</p>

<p>
  <strong>Requests:</strong>
  <%= @domain.requests %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpellChecker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-static-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="brand" href="/">SpellChecker</a>
				<div class="container-fluid"> 
					<ul class="nav ">
						<% if (!current_user)%>
							<li> <%= link_to t("sing_in"), user_omniauth_authorize_path(:doorkeeper) %></li>
						<% else %>
							<li><%= link_to t("sing_out"), destroy_user_session_path  %></li>
						<% end %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<%=t("menu.documentation")%>
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<% %W(install api languages).each do |m|%>
									<li><%= link_to t("documentation.#{m}.menu"),  send("documentation_#{m}_path")%></li>
								<%end%>
							</ul>
						</li>
						<% if (!current_user)%>
							<li><%= link_to t("menu.domains"), domains_path  %></li>
						<% end %>
					</ul>
					<ul class="nav pull-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<%=t("langs.#{I18n.locale}")%>
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<%$available_locales.each do |l|%>
									<li><%= link_to t("langs.#{l}"),  locale_path(locale: l)%></li>
								<%end%>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="main">
				<div id="bootstrap_flash">
					<%= bootstrap_flash %>
				</div>
				<%= yield %>
			</div>
		</div>
		<div id="footer" style="position:fixed; bottom: 0px;z-index: 1;">
			<p>
				&copy; White Sandwitch Studio <%=Date.current.year%>
			</p>
		</div>
	</div> <!-- /container -->
	
</body>
</html>

app/views/main/index.html.erb
<link rel="stylesheet" type="text/css" media="screen" href="/jquery.spellchecker.min.css" />
<style type="text/css">
  #text-content {width:400px;border:1px solid #888;padding:1em;margin:0 0 1em 0;}
</style>
<p>This example demonstrates how the <em>html parser</em> can be used to check the spelling of text within a DOM tree.</p>

<div contenteditable=true id="text-content">
	Вот это пл<strong>оoх</strong>ое слово. Она былiа написана с ошибками.
</div>
<select id="language">
  <option value="ru" selected>Russian</option>
  <option value="en">English</option>
  <option value="es" >Spanish</option>
  <option value="fr">French</option>
  <option value="nl">Dutch</option>
</select>
<button id="check-textarea">
  Check Spelling
</button>&nbsp;
</div>
<script type="text/javascript" src="/jquery.spellchecker.js"></script>
<script type="text/javascript">
	(function() {
		var spellchecker;

		  // Init the html spellchecker
		  spellchecker = new $.SpellChecker('#text-content', {
			lang: "en",
			parser: 'html',
			webservice: {
			  path: '/api/check',
			  driver: 'PSpell'
			},
			suggestBox: {
			  position: 'below'
			}
		  });

		  // Bind spellchecker handler functions
		  spellchecker.on('check.success', function() {
			alert('There are no incorrectly spelt words!');
		  });
		  
		  // Check the spelling
		  $("#check-textarea").click(function(e){
			spellchecker.check();
		  });
		  
		  // Change the language
		  $('#language').change(function() {
			spellchecker.setLang(this.value);
		  }).trigger('change');
		
	})();
</script>
<br />
<div>
	<% Domain.all.each do |d| %>
		<%= d.name %> : <%= "words: #{d.words.to_i}, requests: #{d.requests.to_i}" %><br>
	<% end %>
</div>
<br />
Available languages: 
<% available_languages.each do |l| %>
	<%= t("lang.#{l}") %>
<% end %>